#ifndef __V24_COMMANDS_H__
#define __V24_COMMANDS_H__


// V24 Kommandos

#define LEFT_MOTOR_SPEED_FORWARD			0x01
#define LEFT_MOTOR_SPEED_BACKWARD			0x11 
#define RIGHT_MOTOR_SPEED_FORWARD			0x02
#define RIGHT_MOTOR_SPEED_BACKWARD			0x12
#define PHOTO_SENSOR					0x22
#define BUTTON_PRESSED					0x33

#endif
